USE MicaDiy ;
CREATE TABLE Customer
(
CUS_CODE INT ,
CUS_LNAME VARCHAR,
CUS_FNAME VARCHAR,
CUS_INITIAL CHAR,
CUS_AREACODE INT,
CUS_PHONE INT,
CUS_BALANCE INT,
CONSTRAINT CUS_CODE_PK PRIMARY KEY(CUS_CODE)
)

CREATE TABLE Invoice
(
INV_NUMBER INT ,
CUS_CODE INT ,
INV_DATE DATE,
CONSTRAINT INV_NUMBER_PK PRIMARY KEY(INV_NUMBER),
CONSTRAINT CUS_CODE_FK1 FOREIGN KEY(CUS_CODE) REFERENCES Customer(CUS_CODE)
)

CREATE TABLE Vendor
(
V_CODE INT ,
V_NAME VARCHAR,
V_CONTACT VARCHAR,
V_AREACODE INT,
V_PHONE INT,	
V_STATE VARCHAR,
V_ORDER CHAR,
CONSTRAINT V_CODE_PK PRIMARY KEY(V_CODE)
)

CREATE TABLE Product
(
P_CODE VARCHAR ,
P_DESCRIPT VARCHAR,
P_INDATE DATE,
P_ONHAND INT,
P_MIN INT,
P_PRICE DECIMAL,
P_DISCOUNT DECIMAL,
V_CODE INT,
CONSTRAINT P_CODE_PK PRIMARY KEY(P_CODE) ,
CONSTRAINT V_CODE_FK2 FOREIGN KEY(V_CODE) REFERENCES Vendor(V_CODE) 
 
)




CREATE TABLE LINE
(

INV_NUMBER INT ,
LINE_NUMBER INT,
P_CODE VARCHAR,
LINE_UNITS INT,
LINE_PRICE DECIMAL,
CONSTRAINT LINE_PK PRIMARY KEY(INV_NUMBER ,LINE_NUMBER), /* THIS IS A MULTI LINE COMMENT */ 
CONSTRAINT P_CODE_FK3 FOREIGN KEY(P_CODE) REFERENCES Product(P_CODE) -- SINGLE LINE COMMENT
)


